INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (20,"HUNTINGTON",435);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (21,"FAIRFIELD",722);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (22,"WATERVILLE",364);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (23,"ALBANY",560);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (24,"MILTON",71);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (25,"SHELBURNE",36);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (26,"HIGHGATE",709);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (27,"ALBURGH",1597);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (28,"ST ALBANS",68);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (29,"MAIDSTONE",298);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (30,"WESTFIELD",364);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (31,"HYDE PARK",121);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (32,"LOWELL",458);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (33,"STOWE",112);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (34,"GEORGIA",175);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (35,"JERICHO",596);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (36,"HINESBURG",1008);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (37,"HOLLAND",434);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (38,"MONTGOMERY",832);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (39,"BOLTON",188);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (40,"JOHNSON",469);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (41,"LOOMFIELD",1270);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (42,"GUILDHALL",113);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (43,"MORRISTOWN",283);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (44,"ENOSBURG",83);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (45,"RICHMOND",621);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (46,"CHARLESTON",571);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (47,"COVENTRY",192);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (48,"ST GEORGE",360);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (49,"AVERILL",51);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (50,"WARREN GORE",6);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (51,"FAIRFAX",690);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (52,"SWANTON",507);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (53,"FRANKLIN",908);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (54,"SHELDON",377);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (55,"WILLISTON",816);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (56,"GRAND ISLE",1358);
INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (57,"WESTFORD",546);

INSERT INTO `townmeters`(`id`, `town`, `numOfMeters`) VALUES (58,"CAMBRIDGE",1464);

